### ISSUE TITLE
How to use this tool?

### ISSUE THREAD

**Issue by moti477** [LukeFZ/MsixvcPackageDownloader#1]
Can you explain please how to use this tool, because when I paste the response url it's crash to desktop.
Thank you.

**Comment by LukeFZ** [comment]
Did you completely sign in after visiting the url the tool printed to the console? You should be redirected to a completely white page after login (at least for me) and at that point you should copy the url from the browser back into the console window.

**Comment by moti477** [comment]
Thank you for reply.
That exactly what I did.

**Comment by LukeFZ** [comment]
Alright, can you post the error message you're getting?
If the window closes too fast you can run the program from a cmd window, that way it won't close after throwing the exception.
You should also redact the access_token and refresh_token values if the exception includes the url you pasted into the window.

**Comment by moti477** [comment]
I did what you suggest in cmd, and the error I get is:
**Error: Failed to authenticate!**

**Comment by LukeFZ** [comment]
Thanks for the report, this seems to be a case of XboxWebApi failing to authenticate your Microsoft account for whatever reason.

Not entirely sure why this happens, but some things you could try are using another Microsoft account and making sure that the account you're logging into has an xbox profile attached.

**Comment by moti477** [comment]
I make my microsoft account to the xbox profile and it didn't work, but when I change the browser to InPrivate window it's working.
Thank you.

**Comment by LukeFZ** [comment]
Awesome, glad you got the issue fixed.
